### ISSUE TITLE
Errors on Windows

### ISSUE THREAD

**Issue by gruebel** [GoogleCloudPlatform/terraform-python-testing-helper#13]
When trying to run any test on Windows, I get following error
```
OSError: [WinError 1314] A required privilege is not held by the client
```
How to reproduce:
Just run the project tests on a windows machine.

**Comment by ludoo** [comment]
Hey, thanks for reporting this! I don't have a Windows machine, but googling around this seems to be due to a permissions issue when copying files. The library injects and removes supporting files (eg tfvars) in the module that is to be tested, so I would start by checking permissions there.

I'm going to close this, since it appears to be a local configuration issue. Feel free of course to reopen if you need additional support!
