### ISSUE TITLE
terragrunt python testing helper?

### ISSUE THREAD

**Issue by marshall7m** [GoogleCloudPlatform/terraform-python-testing-helper#23]
Just wondering if there's anything brewing in regards to incorporating a wrapper for running Terragrunt commands. Something like:

```
tg = tftest.TerragruntTest(fixtures_dir)
tg.plan_all(output=True)
```

**Comment by ludoo** [comment]
Not planned, but looks like a nice addition. I'm not really familiar with Terragrunt, if you have the time to sketch an initial implementation, I can give it a shot as soon as I have some time. Or feel free of course to send a PR if you prefer.

**Comment by marshall7m** [comment]
Great I'll try to get rough an implementation sometime next week. And great job on it so far, I've been using it as a workaround to my inexperience with writing Terratest in Go.

**Comment by DavidTamLloyds** [comment]
hello I saw there was a branch https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/tree/terragrunt-support with terragrunt stuff in there but this is it.  how far is it from general availability?  I looked at the branch and there isnt doc. ?  is there a quick way I could try that out (or it really isnt ready yet and still WIP?)

**Comment by ludoo** [comment]
David, I unfortunately fell behind on integrating that into the master branch due to regular workload. Going from memory, we were still unsure on how to integrate documentation for the myriad new args into the code, but the branch might be usable as is. Can you give it a try, and I'll make an effort to find some time and finish the work in the meantime.

**Comment by davidtam** [comment]
@marshall7m @ludoo ok I have just got round to take a look.  2 things:
https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/blob/076e5aee01468ea17ba70436a0cec8c6415cca14/tftest.py#L67
I think it would be better to just have command flag starts with terragrunt to just delegated to tg (without hardcode remap)?  This saves a bit of code but also nothing to maintain when tg decided to change their cli options.  Plus there is less tests to write if you were to write them

https://github.com/GoogleCloudPlatform/terraform-python-testing-helper/blob/076e5aee01468ea17ba70436a0cec8c6415cca14/test/test_tg_all.py#L28
Are you guys happy with me commiting tests to this branch?

Otherwise it looks to work enough to me.

**Comment by ludoo** [comment]
David, sorry for the huge lag in replying. I planned on setting aside some time for this, but it did not happen (yet). How do you prefer to proceed? Are you ok working on a branch in this repo?

**Comment by davidtam** [comment]
ok yes a branch is fine I will do that and start with adding some test.  we let you know when I have got something

**Comment by davidtam** [comment]
Thanks @ludoo for merging in #29 #32 !
This could probably closed?
